import React from 'react'

import { Header } from 'semantic-ui-react'

class Home extends React.Component {
  render () {
    return (
      <React.Fragment>
        <Header as="h1">Welcome to the Virtual Tour</Header>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi malesuada turpis nisl, sed tristique est consectetur eu. Vivamus suscipit quam quis lorem fermentum aliquet. Pellentesque scelerisque accumsan vestibulum. Suspendisse potenti. Nullam lacinia iaculis ipsum ac convallis. Donec tincidunt venenatis ligula id pretium. Morbi ut blandit neque. Phasellus sit amet augue semper, rhoncus massa eget, pretium ligula. Sed et tristique nulla. Donec volutpat diam velit, eget bibendum leo fringilla ut. Nulla et lacus tempor sem dignissim commodo vitae eu sem. Nunc at sapien massa. Ut eu viverra eros. Nulla ullamcorper commodo lectus, vitae imperdiet velit tincidunt eu. Vestibulum eget viverra elit.</p>

        <p>Nunc tempor quam ac risus molestie, eget scelerisque justo vehicula. Aliquam eu aliquam neque. Mauris pellentesque tristique sapien, eu finibus risus tristique quis. Praesent at malesuada felis. Suspendisse iaculis sodales consequat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris fermentum tincidunt maximus.</p>

        <p>Quisque molestie mattis sapien sed viverra. Morbi euismod magna augue, ut egestas orci maximus in. Mauris blandit odio quis massa bibendum ultricies eu ut neque. Curabitur pellentesque mauris eu neque iaculis accumsan. Nulla eu massa odio. In id ligula et lorem rutrum sollicitudin. Cras mi risus, aliquet vel ullamcorper id, aliquam a massa. Ut varius ex mi, at euismod libero commodo vitae. Cras sed ligula in augue malesuada commodo nec eget augue. Sed commodo odio et vestibulum tristique.</p>

        <p>Sed dapibus massa a tincidunt vehicula. Integer velit mi, vestibulum nec ex hendrerit, accumsan tristique sapien. Donec at tincidunt dolor. Curabitur eleifend ut lorem vel faucibus. Pellentesque mattis nisi eget egestas tincidunt. Nam posuere dui lacus, vitae blandit metus tincidunt ut. Morbi quis diam porta, cursus augue a, facilisis orci. Nullam mi orci, ornare eget dui non, lacinia tincidunt nibh.</p>

        <p>Vivamus placerat scelerisque tincidunt. Integer elementum ut leo et mollis. Aenean nunc nulla, maximus eget consequat vel, sodales sed magna. Donec nec nulla arcu. Donec et eros massa. Praesent tristique tempor massa, nec maximus nisi congue ac. Aliquam quis felis arcu. Donec tincidunt at felis vitae egestas. Pellentesque facilisis et nunc sit amet finibus. Suspendisse potenti. Suspendisse potenti. Etiam elementum metus vel nibh bibendum gravida. Curabitur elit nulla, pellentesque ut</p> venenatis sit amet, pretium vel nibh.

        <p>Sed efficitur lacus id tortor interdum convallis. Curabitur hendrerit porttitor tempus. Morbi porttitor metus mi, in dignissim justo ullamcorper et. Nam vitae lacus commodo, feugiat risus in, pellentesque lacus. Nullam libero turpis, interdum eget libero at, sollicitudin blandit augue. Sed eu feugiat metus. Nulla tincidunt, nulla luctus accumsan suscipit, magna magna rhoncus libero, non lacinia felis massa at lacus. Proin tincidunt, quam nec posuere facilisis, magna quam laoreet libero, eu</p> dignissim turpis neque in neque. Proin tincidunt pharetra pharetra. Curabitur fringilla lacinia nulla in laoreet. Sed euismod varius imperdiet. Curabitur sodales mattis turpis et ultricies. Fusce vestibulum odio nec magna varius sollicitudin. Aliquam non sem et lacus rutrum scelerisque convallis a nunc. Sed non libero nisi. In tempor, tellus a pretium viverra, eros neque accumsan ex, id pharetra turpis libero imperdiet magna.

        <p>Etiam id nulla risus. Mauris et neque ante. Suspendisse potenti. Aenean vel congue leo. Donec vehicula nulla vitae bibendum semper. Nullam ac ullamcorper nisl. Morbi vehicula dictum magna, ut ultricies elit aliquam a. Aliquam dolor nisl, aliquam id diam vitae, dignissim efficitur arcu. Etiam at malesuada nisi. Suspendisse potenti. Morbi lacinia magna lectus, ut suscipit nisl laoreet sed. Nam sit amet diam congue, congue velit quis, lobortis magna. Nam quis tortor ut odio tincidunt blandit.</p>

        <p>Morbi a diam nulla. Integer iaculis arcu sodales eros imperdiet, non auctor magna cursus. Aliquam quis purus felis. Donec pretium eros vel orci rhoncus, non fermentum massa hendrerit. Vestibulum arcu leo, vulputate at diam id, tincidunt fringilla lorem. Duis aliquet, dui non egestas molestie, urna ante cursus ipsum, at tincidunt lorem erat varius dolor. Maecenas bibendum bibendum tortor, in cursus lorem viverra eget. Fusce lacinia nisi quis nisi tempor feugiat. Nulla viverra velit vel elit</p> convallis, vel aliquet tellus vehicula. Curabitur enim sapien, mollis sit amet efficitur in, finibus accumsan odio. Etiam feugiat bibendum enim, sed malesuada ante volutpat ac.

        <p>Mauris feugiat eros metus, eget faucibus ex pulvinar in. Sed vitae scelerisque augue. Mauris eu nisi magna. Fusce ullamcorper interdum risus. Donec quis dictum dolor. In hac habitasse platea dictumst. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas nulla turpis, laoreet ac quam in, gravida rutrum libero. Sed imperdiet rutrum hendrerit. Nulla nisl elit, facilisis et lorem in, pellentesque eleifend ante. Morbi malesuada tortor rhoncus</p> risus laoreet posuere. Sed consectetur erat libero, ac interdum libero interdum ac.

        <p>Fusce arcu tellus, posuere sit amet fringilla a, aliquet at quam. Aliquam volutpat pellentesque vulputate. Suspendisse ultrices, nisl id dignissim scelerisque, ex odio cursus purus, quis aliquet tellus arcu vitae felis. Mauris eget fermentum metus, nec porttitor neque. Vivamus quis maximus nisl, vitae vestibulum urna. In lorem dui, dictum sit amet luctus quis, feugiat quis ante. Aliquam fringilla nisi et ante elementum, ullamcorper malesuada mi efficitur. Aenean hendrerit mollis purus nec</p> iaculis. Donec justo nulla, efficitur vel dolor a, sagittis vehicula est. Ut consectetur fringilla velit sed aliquet. In neque tortor, lobortis semper dui ac, pretium tempor eros. Sed consequat feugiat tortor, non rhoncus justo bibendum eu. Maecenas hendrerit condimentum tellus, non fringilla urna pretium vel. Cras risus erat, venenatis et faucibus sit amet, vestibulum ut magna.

        <p>Nulla purus augue, varius nec pulvinar ut, tempus a ex. Praesent tincidunt justo non mauris porttitor pharetra. Nullam rutrum gravida lacus id consequat. Mauris quis sapien vitae lectus convallis congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum et dapibus eros. Donec egestas nulla sed purus malesuada varius. Quisque posuere dui a libero vulputate tempor. Maecenas finibus tellus quis auctor condimentum. Nam ligula justo, faucibus</p> in pharetra imperdiet, auctor sed turpis. Donec vel tortor sit amet odio sagittis rutrum ut at lacus. Vivamus ut tristique augue, ut cursus justo. Pellentesque auctor eros sed elit semper posuere. Nullam eros elit, dapibus vel facilisis at, aliquam et eros. Praesent egestas, justo eget venenatis semper, nunc ipsum iaculis lorem, id imperdiet nibh velit a nisi. In metus tortor, vulputate et sagittis sed, ultrices in ipsum.

        <p>Aliquam ornare ante sed lobortis ultrices. Fusce convallis bibendum tincidunt. Ut fermentum mauris id tempor hendrerit. In euismod ac dui quis interdum. Ut feugiat, mauris a pulvinar commodo, quam massa consectetur enim, ac placerat ex enim vitae sem. Phasellus viverra eros a purus luctus ultricies. Sed id ipsum rhoncus, porttitor arcu a, bibendum odio. Suspendisse vulputate euismod velit.</p>
        </React.Fragment>
    )
  }
}

export default Home
